# Generated by Django 3.2.8 on 2021-11-03 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=30)),
                ('cust_contact', models.IntegerField(unique=True)),
                ('cust_email', models.EmailField(max_length=30, unique=True)),
                ('cust_password', models.CharField(max_length=30)),
                ('cust_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=30)),
                ('item_price', models.FloatField()),
                ('item_photo', models.ImageField(upload_to='food_images/')),
                ('item_status', models.CharField(max_length=50)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app9.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_time', models.TimeField(auto_now_add=True)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app9.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('quantity_no', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app9.food')),
                ('ord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app9.order')),
            ],
        ),
    ]
